# Generated by Django 4.2.8 on 2025-11-04 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_internshippost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('success', 'Accepted'), ('declined', 'Declined'), ('interview_pending', 'Interview Scheduled'), ('interview_success', 'Interview Passed'), ('interview_unsuccess', 'Interview Failed'), ('pending_final_decision', 'Pending Final Decision')], default='pending', max_length=30)),
                ('cover_letter', models.TextField(help_text='Explain why you are a good fit for this internship')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('employer_notes', models.TextField(blank=True, help_text='Internal notes from employer (not visible to intern)')),
                ('additional_documents', models.ManyToManyField(blank=True, help_text='Select relevant documents to include with your application', related_name='applications', to='core.interndocument')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.internprofile')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.internshippost')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status', 'applied_at'], name='application_status_89c2ad_idx'), models.Index(fields=['intern', 'status'], name='application_intern__2363ed_idx')],
                'unique_together': {('internship', 'intern')},
            },
        ),
    ]
