# Generated by Django 4.2.8 on 2025-11-04 10:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('bio', models.TextField(blank=True, help_text='Tell us about yourself')),
                ('current_location', models.CharField(blank=True, max_length=200)),
                ('current_municipality', models.CharField(blank=True, max_length=100)),
                ('current_province', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industries', models.ManyToManyField(blank=True, related_name='interested_interns', to='core.industry')),
            ],
            options={
                'verbose_name': 'Intern Profile',
                'verbose_name_plural': 'Intern Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Describe your responsibilities and achievements')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience_set', to='core.internprofile')),
                ('skills_used', models.ManyToManyField(blank=True, related_name='work_experiences', to='core.skill')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['province', 'municipality'],
                'unique_together': {('municipality', 'province')},
            },
        ),
        migrations.AddField(
            model_name='internprofile',
            name='preferred_locations',
            field=models.ManyToManyField(blank=True, related_name='interested_interns', to='core.location'),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='interns', to='core.skill'),
        ),
        migrations.AddField(
            model_name='internprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])])),
                ('company_description', models.TextField(help_text='Describe your company and what you do')),
                ('company_website', models.URLField(blank=True)),
                ('contact_person', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('company_location', models.CharField(max_length=200)),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('industries', models.ManyToManyField(blank=True, related_name='employers', to='core.industry')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('grade', models.CharField(blank=True, help_text='e.g., Distinction, Pass, GPA 3.5', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Additional details about your studies')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_set', to='core.internprofile')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education Records',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InternDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('cv', 'CV/Resume'), ('qualification', 'Qualification Certificate'), ('id', 'ID Document'), ('transcript', 'Academic Transcript'), ('other', 'Other')], max_length=20)),
                ('document', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('version', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.internprofile')),
            ],
            options={
                'verbose_name': 'Intern Document',
                'verbose_name_plural': 'Intern Documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['intern', 'document_type', 'is_latest'], name='core_intern_intern__47247d_idx')],
            },
        ),
    ]
