# Generated by Django 4.2.8 on 2025-11-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Describe the internship opportunity')),
                ('requirements', models.TextField(help_text='What qualifications and skills are required?')),
                ('responsibilities', models.TextField(help_text='What will the intern be doing?')),
                ('location', models.CharField(help_text='Full address or area', max_length=200)),
                ('municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('duration_months', models.IntegerField(help_text='Duration in months')),
                ('stipend', models.DecimalField(blank=True, decimal_places=2, help_text='Monthly stipend (optional)', max_digits=10, null=True)),
                ('start_date', models.DateField(help_text='Expected start date')),
                ('application_deadline', models.DateField(help_text='Last date to apply')),
                ('is_active', models.BooleanField(default=True, help_text='Is this internship still accepting applications?')),
                ('is_published', models.BooleanField(default=False, help_text='Is this internship visible to interns?')),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_posts', to='core.employerprofile')),
                ('industry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internship_posts', to='core.industry')),
                ('skills_required', models.ManyToManyField(blank=True, related_name='internship_posts', to='core.skill')),
            ],
            options={
                'verbose_name': 'Internship Post',
                'verbose_name_plural': 'Internship Posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'is_published'], name='core_intern_is_acti_51afb6_idx'), models.Index(fields=['application_deadline'], name='core_intern_applica_57d2df_idx')],
            },
        ),
    ]
