"""
Django settings for lwazi_blue project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-c4^2_sx@3yalo&euh$f$gwpdzow9le%8awdt%r(j497%hykd45')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# =====================================================
# SECURITY SETTINGS
# =====================================================

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
FILE_UPLOAD_PERMISSIONS = 0o644

# Allowed file extensions for uploads
ALLOWED_IMAGE_EXTENSIONS = ['jpg', 'jpeg', 'png', 'gif', 'webp']
ALLOWED_DOCUMENT_EXTENSIONS = ['pdf', 'doc', 'docx', 'txt']
MAX_FILE_SIZE = 5 * 1024 * 1024  # 5MB

# Security Headers - Production only (HTTPS required)
if DEBUG:
    print("Security Headers - Development", DEBUG)
    # Development settings - HTTP friendly
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    SECURE_HSTS_SECONDS = 0
else:
    print("Security Headers - Production", DEBUG)
    # Force HTTPS in production
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Prevent the site from being embedded in <iframe> tags to protect against clickjacking attacks.
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Cache timeouts for different content types
CACHE_TTL = {
    # 'homepage': 60 * 15,  # 15 minutes
    'homepage': 0,  # 15 minutes
    'blog_list': 60 * 10,  # 10 minutes
    'blog_detail': 60 * 30,  # 30 minutes
    'matching_results': 60 * 5,  # 5 minutes
    'profile_completion': 60 * 60,  # 1 hour
}


# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_SAVE_EVERY_REQUEST = False
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# CSRF Protection
CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = False
if DEBUG:
    # More lenient in development
    CSRF_COOKIE_SAMESITE = 'Lax'
    CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']
else:
    # Strict in production
    CSRF_COOKIE_SAMESITE = 'Strict'

# Password validation strength
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    
    # Local apps
    'accounts',
    'core',
    'applications',
    'blog',
    'notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.RateLimitMiddleware',  # Rate limiting for auth endpoints
]

ROOT_URLCONF = 'lwazi_blue.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'core.context_processors.unread_counts',
            ],
        },
    },
]

WSGI_APPLICATION = 'lwazi_blue.wsgi.application'


# =====================================================
# DATABASE CONFIGURATION
# =====================================================
# Development: SQLite3 (default)
# Production: PostgreSQL via DATABASE_URL environment variable

DATABASE_URL_EXISTS = os.getenv('DATABASE_URL')
if DEBUG or not DATABASE_URL_EXISTS or DATABASE_URL_EXISTS == '':
    # Development - Use SQLite
    print("Database - Development Mode: SQLite3")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
            # Performance optimizations for SQLite
            'OPTIONS': {
                'timeout': 20,
            },
            'CONN_MAX_AGE': 600,  # Connection pooling
        }
    }
else:
    # Production - Use DATABASE_URL
    print("Database - Production Mode: PostgreSQL/MySQL from DATABASE_URL")
    database_url = os.getenv('DATABASE_URL')
    
    if database_url:
        # Parse DATABASE_URL manually
        # Format: postgres://user:password@host:port/database
        # or: postgresql://user:password@host:port/database
        # or: mysql://user:password@host:port/database
        
        try:
            import re
            from urllib.parse import urlparse, unquote
            
            parsed = urlparse(database_url)
            
            # Map database schemes to Django engines
            engine_map = {
                'postgres': 'django.db.backends.postgresql',
                'postgresql': 'django.db.backends.postgresql',
                'mysql': 'django.db.backends.mysql',
                'sqlite': 'django.db.backends.sqlite3',
            }
            
            engine = engine_map.get(parsed.scheme, 'django.db.backends.postgresql')
            
            # For SQLite, the path is the database name
            if parsed.scheme == 'sqlite':
                db_name = parsed.path.lstrip('/')
                DATABASES = {
                    'default': {
                        'ENGINE': engine,
                        'NAME': BASE_DIR / db_name if not db_name.startswith('/') else db_name,
                    }
                }
            else:
                # For PostgreSQL/MySQL
                DATABASES = {
                    'default': {
                        'ENGINE': engine,
                        'NAME': parsed.path.lstrip('/'),
                        'USER': unquote(parsed.username) if parsed.username else '',
                        'PASSWORD': unquote(parsed.password) if parsed.password else '',
                        'HOST': parsed.hostname or 'localhost',
                        'PORT': parsed.port or (5432 if 'postgres' in parsed.scheme else 3306),
                        'CONN_MAX_AGE': 600,
                        'OPTIONS': {
                            'connect_timeout': 10,
                        },
                    }
                }
            
            print(f"✅ Using database: {parsed.scheme}://{parsed.hostname}/{parsed.path.lstrip('/')}")
            
        except Exception as e:
            print(f"⚠️  Error parsing DATABASE_URL: {e}")
            print("⚠️  Falling back to SQLite")
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }
    else:
        # No DATABASE_URL provided - fall back to SQLite with warning
        print("⚠️  WARNING: DEBUG=False but DATABASE_URL not set!")
        print("⚠️  Falling back to SQLite - NOT RECOMMENDED FOR PRODUCTION")
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


# =====================================================
# CACHING CONFIGURATION
# =====================================================

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'lwazi-blue-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        },
        'TIMEOUT': 300,  # 5 minutes default
    }
}


# Password validation (configured above in SECURITY SETTINGS)


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Johannesburg'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# =====================================================
# EMAIL CONFIGURATION (Using Python smtplib)
# =====================================================
# Using custom email service instead of Django's email backend
# See: core/email_service.py

# Email settings loaded from environment variables
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@lwazi-blue.co.za')
ENABLE_EMAIL_NOTIFICATIONS = os.getenv('ENABLE_EMAIL_NOTIFICATIONS', 'True') == 'True'
# SMTP Configuration (set these in .env for production)
# EMAIL_HOST = smtp.gmail.com (or your SMTP server)
# EMAIL_PORT = 587 (or 465 for SSL)
# EMAIL_USE_TLS = True
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'noreply@lwazi-blue.co.za')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'noreply@lwazi-blue.co.za')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_PORT = os.getenv('EMAIL_PORT', 587)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')

# In development without credentials, emails will be printed to console
# In production with credentials, emails will be sent via SMTP

# Login/Logout URLs
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'core:dashboard'
LOGOUT_REDIRECT_URL = 'core:home'

# Matching Algorithm Weights (Configurable)
MATCHING_WEIGHTS = {
    'skills': 0.40,
    'industry': 0.25,
    'location': 0.20,
    'qualification': 0.15,
}
