# Generated by Django 4.2.8 on 2025-11-04 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_application_submitted', models.BooleanField(default=True, help_text='Receive email when you submit an application')),
                ('email_application_status', models.BooleanField(default=True, help_text='Receive email when application status changes')),
                ('email_new_message', models.BooleanField(default=True, help_text='Receive email for new messages')),
                ('email_matched_internships', models.BooleanField(default=True, help_text='Receive email about new matched internships')),
                ('email_deadline_reminders', models.BooleanField(default=True, help_text='Receive email reminders about deadlines')),
                ('internal_notifications', models.BooleanField(default=True, help_text='Receive internal notifications in the platform')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('application_status_update', 'Application Status Update'), ('new_message', 'New Message'), ('new_matched_internship', 'New Matched Internship'), ('internship_deadline_reminder', 'Internship Deadline Reminder')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Link to related item', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
